<?php

/**
 * Implements hook_custom_theme().
 */
function dynamic_theme_custom_theme() {

  // Load current user
  global $user;

  // Check current page is 'node/%nid%/nid'
  if(current_path() == 'node/%node/edit'){
    // Check current user role is 'driver'
    $roles = $user->roles;
    if(in_array('driver',$roles)){
      // return admin theme for these page
      return variable_get('admin_theme');
    }
  }

  // Check current page is 'node/%nid%/nid'
  if(current_path() == 'node/add/article'){
    // Check current user role is 'driver'
    $roles = $user->roles;
    if(in_array('driver',$roles)){
      // return default theme for these page
      return variable_get('theme_default');
    }
  }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function dynamic_theme_preprocess_html(&$vars)  {
  $path = drupal_get_path_alias();

  $aliases = explode('/', $path);

  foreach($aliases as $alias) {
    $vars['classes_array'][] = drupal_clean_css_identifier($alias);
  }
  //krumo($path); exit;
}


