<?php

/**
 * Implements hook_menu().
 */
function custom_ajax_file_upload_menu() {

   $items['custom_ajax_file_upload'] = array(
    'title' => 'Custom ajax file upload',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_ajax_file_upload_form'),
    'access callback' => 'user_is_logged_in',
  );

  return $items;
}


function custom_ajax_file_upload_form($form, &$form_state) {

$form = [];
$form['user_picture'] = [
  //'#title' => 'User Photo',
  '#type' => 'file',
  //'#upload_location' => 'public://',
  ];

/*$form['submit'] = [
   '#type' => 'submit',
   '#value' => 'Save',
 ];*/
 $form['submit'] = [
   '#type' => 'submit',
   '#value' => 'Save',
   '#limit_validation_errors' => array(array('user_picture')),
   '#submit' => array('user_profile_image_submit'),
   '#validate' => array('user_profile_image_validate'),
  ];

  $form['#attached']['js'] = array(
    drupal_get_path('module', 'custom_ajax_file_upload') . '/js/auto_submit.js',
  );
  return $form;
}

function user_profile_image_validate($form, &$form_state) {
 $file = file_save_upload('user_picture', array(
    'file_validate_is_image' => array(),
    'file_validate_extensions' => array('png gif jpg jpeg'),
  ));
  if ($file) {
    if ($file = file_move($file, 'public://')) {
      $form_state['values']['user_picture'] = $file;
    }
    else {
      form_set_error('user_picture', t('Failed to write the uploaded file the site\'s file folder.'));
    }
  }
  else {
    form_set_error('user_picture', t('No file was uploaded.'));
  }
}

/*function custom_ajax_file_upload_form_validate($form, &$form_state) {
kpr($form_state); exit();
}
function custom_ajax_file_upload_form_submit($form, &$form_state) {
kpr($form_state); exit();
}*/


function user_profile_image_submit($form, &$form_state) {
  global $user;
  $uid = $user->uid;
  $account = user_load($uid);
  $file = $form_state['values']['user_picture'];
  unset($form_state['values']['user_picture']);
  $file->status = FILE_STATUS_PERMANENT;
  /* Check & delete if file already exist */
  // Get file id of profile photo
  $fid = isset($account->picture->fid) ? $account->picture->fid : '';
  if ($fid) {
    $exist_file = file_load($fid);
    file_delete($exist_file, 'TRUE');
    unset($account->picture);
    user_save($user);
  }
  /* Check & delete if file already exist */
  file_save($file);
  file_usage_add($file, 'custom_ajax_file_upload', 'user', $user->uid);
  $edit['picture'] = $file;
  user_save($account, $edit);
  drupal_set_message(t('Image uploaded successfully'));
}


/**
* Implements hook_theme().
*/
function custom_ajax_file_upload_theme() {
  return array(
    'custom_ajax_file_upload_form' => array(
      'render element' => 'form',
    ),
  );
}


/**
* Implements theme_mymodule_thumb_upload theme callback.
*/
function theme_custom_ajax_file_upload_form($variables) {

 $form = $variables['form'];
 //kpr($form);
 unset($form['user_picture']['#theme_wrappers']);
  $output = '';

  $output .= '<div class="user_pic_imgbg">
                 <a href="#" id="edit_img" class="btn edit_btn">
                 <span>Your Photo</span>
                 </a>
             </div>
             <div class= "user_img" style="display:none;">
             <div>' . drupal_render($form['user_picture']) . '</div>
             <div style="margin-top: -25px; margin-left: 19px;">' . drupal_render($form['submit']) . '</div>
             </div>';
$output .= drupal_render_children($form);

return  $output;
 }
