<?php

/**
 * Implements hook_schema().
 */
function custom_form_schema() {

  $schema['mydata'] = array(
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
       ),

      'name' => array(
        'type' => 'varchar',
        'length' => 255,
       ),
      'email' => array(
        'type' => 'varchar',
        'length' => 255,
       ),
      ),
    'primary key' => array('id'),
  );
  return $schema;
}

